FROM pytorch/pytorch:2.4.0-cuda11.8-cudnn9-devel
USER root
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG HTTP_PROXY
ARG HTTPS_PROXY
ENV http_proxy=$HTTP_PROXY
ENV https_proxy=$HTTPS_PROXY

RUN mkdir -p /app/ml_bot
WORKDIR /app/ml_bot

RUN apt-get update && apt-get install -y \
    zip \
    unzip \
    git \
    curl \
    tmux \
    valgrind \
    libssl-dev \
    pkg-config  \
    htop \
    wget
# TA-Libのビルドとインストール
# TA-Libのインストール
RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
    tar -xzf ta-lib-0.4.0-src.tar.gz && \
    cd ta-lib && \
    ./configure --prefix=/usr && \
    make && \
    make install && \
    cd .. && \
    rm -rf ta-lib ta-lib-0.4.0-src.tar.gz


RUN curl -sSL https://install.python-poetry.org | python3 -  
ENV PATH="/root/.local/bin:$PATH"
#WORKDIR /root/src/.devcontainer/environment/llama2/
#RUN poetry install
#RUN poetry --version
RUN poetry config virtualenvs.create false
ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:${LD_LIBRARY_PATH}



