objective: huber
alpha: 0.9
boosting_type: gbdt
learning_rate: 0.01
num_leaves: 31
max_depth: -1
min_child_samples: 200
subsample: 0.6
colsample_bytree: 0.5
subsample_freq: 5
reg_alpha: 1.0
reg_lambda: 1.0
n_estimators: 6000
random_state: 42
verbosity: -1
early_stopping_rounds: 200   # ← ここで設定しておけば関数側は拾うだけ