# conf/strategy/squeeze_momentum.yaml
_target_: labels.squeeze_momentum_indicator_lb_strategy_v2.SqueezeMomentumStrategy
_partial_: true
bb_period:      6
kc_multiplier:  0.9
bb_multiplier:  1.2
linreg_period:  8
stop_loss:      0.025    # 2.5 %
take_profit:    0.03     # 3.0 %
time_exit:      3
threshold:      0.012